### ISSUE TITLE
Bug with PF2 Skin fix

### ISSUE THREAD

**Issue by apoapostolov** [ardittristan/VTTButtonOverflow#2]
Anytime the branch toolbar is redrawn it is pushed away from the parent. 

https://streamable.com/fb8gp0

The issue seems to be here. The additional column when playerlist is expanded:

https://streamable.com/8ve1ng

#controls .active .control-tools {
    left: var(--playerlist-offset);
}

**Comment by ardittristan** [comment]
hm, I'm not able to reproduce, could you maybe send the list of modules that add buttons to the side bar so I can replicate a situation closer to yours?

**Comment by apoapostolov** [comment]
Here's the list: https://rentry.co/mfsz7

I don't think it is up to mods. I tested with Culprit and it still happens. I am on a 15" laptop with 125% scale increment. This might be the issue.

**Comment by ardittristan** [comment]
hm, I can find that moulinette adds a button to the side that is not in the data when the buttons render. Could you maybe type `buttonOverflow.controlAmount` into the console and check how many more/less buttons there are than in the side row (only the static buttons)

**Comment by ardittristan** [comment]
and can you try the new version? I switched the method it fetches the amount of buttons.

**Comment by apoapostolov** [comment]
Same thing, but now there's no switching between proper and wide view when resizing the width of the window. It seems the height is now fixed. 

![image](https://user-images.githubusercontent.com/4083812/117216318-38bfd700-ae08-11eb-9547-9f260b919e6a.png)
