### ISSUE TITLE
BUG - On Foundry 0.8.3 when realod the scene i get a exception

### ISSUE THREAD

**Issue by p4535992** [ardittristan/VTTButtonOverflow#6]
**Environment Details**

Foundry VTT Version: 0.8.3

Operating System: [Linux]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 1.3.1

Modules Enabled?: Yes

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

I updated a old 0.7.9 world to 0.8.3.

When reload the scene i can see this error on the console:

![image](https://i.imgur.com/NDkvSNI.png)

**Comment by ardittristan** [comment]
I don't know why everything is loading slowly, but the error is probably because the game fired the `Ready` hook before the toolbar was loaded in

**Comment by p4535992** [comment]
Sorry the "slowness" it's caused from other stuff, it's just the exception on the console.

**Comment by ardittristan** [comment]
is this still happening?

**Comment by p4535992** [comment]
no i don't see anymore, forgot about this. Ty.
